<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cinder.Core\Cinder.Core.csproj" />
    <ProjectReference Include="..\Cinder.Sidecar\Cinder.Sidecar.csproj" />
    <ProjectReference Include="..\Cinder.Native\Cinder.Native.csproj" />
  </ItemGroup>
</Project>
