<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RootNamespace>Cinder.Reader</RootNamespace>
    <AssemblyName>CinderReader</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="FluentAvaloniaUI" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Markdig" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cinder.Cases\Cinder.Cases.csproj" />
    <ProjectReference Include="..\Cinder.Core\Cinder.Core.csproj" />
  </ItemGroup>
</Project>
