<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Markdig" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="DocumentFormat.OpenXml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cinder.Core\Cinder.Core.csproj" />
    <ProjectReference Include="..\Cinder.Artifacts\Cinder.Artifacts.csproj" />
  </ItemGroup>
</Project>
