using System.Globalization;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;

namespace Cinder.Reports;

/// <summary>
/// Real DOCX export for Cinder reports. Built on top of the official DocumentFormat.OpenXml
/// SDK so the output is a structurally valid Word document — Word, Pages, LibreOffice, and
/// Google Docs all open it cleanly. Layout mirrors the QuestPDF PDF: cover metadata block,
/// per-section bodies (paragraphs + bullets), exhibit cards inline with their parent section,
/// and a final Exhibit Index table.
/// </summary>
internal static class DocxReportWriter
{
    public static void Write(Report report, string markdown, string outputPath)
    {
        ArgumentNullException.ThrowIfNull(report);
        var dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(dir))
        {
            Directory.CreateDirectory(dir);
        }

        using var doc = WordprocessingDocument.Create(outputPath, WordprocessingDocumentType.Document);
        var main = doc.AddMainDocumentPart();
        main.Document = new Document();
        var body = main.Document.AppendChild(new Body());

        // ---- Core properties (Word's "File → Info → Properties" panel).
        var corePart = doc.AddCoreFilePropertiesPart();
        WriteCoreProps(corePart, report);

        // ---- Cover header (title + metadata).
        AppendHeading(body, report.Title, level: 0);
        AppendParagraph(body, $"Template · {ResolveTemplateName(report.TemplateId)}", italic: true);
        AppendParagraph(body, "");
        AppendMetadataRow(body, "Case", report.CaseName);
        AppendMetadataRow(body, "Examiner", report.Examiner);
        AppendMetadataRow(body, "Created (UTC)", report.CreatedUtc.ToString("u", CultureInfo.InvariantCulture));
        AppendParagraph(body, "");

        // ---- Sections.
        foreach (var section in report.Sections)
        {
            AppendHeading(body, section.Title, level: 1);
            foreach (var (kind, text) in BlocksFromMarkdown(section.MarkdownBody))
            {
                switch (kind)
                {
                    case BlockKind.Bullet:
                        AppendBullet(body, text);
                        break;
                    case BlockKind.Heading:
                        AppendHeading(body, text, level: 2);
                        break;
                    default:
                        AppendParagraph(body, text);
                        break;
                }
            }
            foreach (var exhibit in section.Exhibits)
            {
                AppendExhibitCard(body, exhibit, report.Examiner);
            }
        }

        // ---- Exhibit Index.
        var allExhibits = report.Sections.SelectMany(s => s.Exhibits).ToList();
        if (allExhibits.Count > 0)
        {
            AppendHeading(body, "Exhibit Index", level: 1);
            AppendExhibitTable(body, allExhibits);
        }

        // Footer-ish closer.
        AppendParagraph(body, $"Generated by Cinder · github.com/AffluentMods/cinder · {DateTimeOffset.UtcNow:u}", italic: true);
        main.Document.Save();
    }

    private static void WriteCoreProps(CoreFilePropertiesPart corePart, Report report)
    {
        using var stream = corePart.GetStream(FileMode.Create);
        using var writer = new System.Xml.XmlTextWriter(stream, System.Text.Encoding.UTF8);
        writer.WriteStartDocument();
        writer.WriteStartElement("cp", "coreProperties", "http://schemas.openxmlformats.org/package/2006/metadata/core-properties");
        writer.WriteAttributeString("xmlns", "dc", null, "http://purl.org/dc/elements/1.1/");
        writer.WriteAttributeString("xmlns", "dcterms", null, "http://purl.org/dc/terms/");
        writer.WriteAttributeString("xmlns", "xsi", null, "http://www.w3.org/2001/XMLSchema-instance");
        writer.WriteElementString("dc", "title", "http://purl.org/dc/elements/1.1/", report.Title);
        writer.WriteElementString("dc", "creator", "http://purl.org/dc/elements/1.1/", report.Examiner);
        writer.WriteElementString("dc", "subject", "http://purl.org/dc/elements/1.1/", "Cinder forensic report");
        writer.WriteStartElement("dcterms", "created", "http://purl.org/dc/terms/");
        writer.WriteAttributeString("xsi", "type", null, "dcterms:W3CDTF");
        writer.WriteString(report.CreatedUtc.UtcDateTime.ToString("yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture));
        writer.WriteEndElement();
        writer.WriteEndElement();
        writer.WriteEndDocument();
    }

    private static void AppendHeading(Body body, string text, int level)
    {
        var run = new Run(new Text(text) { Space = SpaceProcessingModeValues.Preserve });
        var runProps = new RunProperties(
            new Bold(),
            new FontSize { Val = level switch { 0 => "44", 1 => "32", _ => "26" } },
            new Color { Val = "FF7A1A" });
        run.PrependChild(runProps);
        var para = new Paragraph(run);
        para.PrependChild(new ParagraphProperties(
            new SpacingBetweenLines { Before = "240", After = "120" }));
        body.AppendChild(para);
    }

    private static void AppendParagraph(Body body, string text, bool italic = false)
    {
        var run = new Run(new Text(text ?? "") { Space = SpaceProcessingModeValues.Preserve });
        if (italic)
        {
            run.PrependChild(new RunProperties(new Italic(), new Color { Val = "666666" }));
        }
        var para = new Paragraph(run);
        para.PrependChild(new ParagraphProperties(new SpacingBetweenLines { After = "120" }));
        body.AppendChild(para);
    }

    private static void AppendBullet(Body body, string text)
    {
        var para = new Paragraph(new Run(new Text(text) { Space = SpaceProcessingModeValues.Preserve }));
        para.PrependChild(new ParagraphProperties(
            new Indentation { Left = "360" },
            new NumberingProperties(new NumberingLevelReference { Val = 0 }, new NumberingId { Val = 1 })));
        body.AppendChild(para);
    }

    private static void AppendMetadataRow(Body body, string label, string value)
    {
        var labelRun = new Run(new Text(label + ": ") { Space = SpaceProcessingModeValues.Preserve });
        labelRun.PrependChild(new RunProperties(new Bold(), new Color { Val = "9CA0AB" }));
        var valueRun = new Run(new Text(value) { Space = SpaceProcessingModeValues.Preserve });
        body.AppendChild(new Paragraph(labelRun, valueRun));
    }

    private static void AppendExhibitCard(Body body, Exhibit e, string defaultExaminer)
    {
        AppendHeading(body, $"{e.Id} · {e.Title}", level: 2);
        if (!string.IsNullOrEmpty(e.Description))
        {
            AppendParagraph(body, e.Description);
        }
        if (!string.IsNullOrEmpty(e.FilePath))
        {
            AppendMetadataRow(body, "File", e.FilePath);
        }
        if (e.FileSize.HasValue)
        {
            AppendMetadataRow(body, "Size", $"{e.FileSize.Value:N0} bytes");
        }
        if (!string.IsNullOrEmpty(e.Sha256))
        {
            AppendMetadataRow(body, "SHA-256", e.Sha256);
        }
        AppendMetadataRow(body, "Captured", $"{e.CapturedUtc:u} by {e.Examiner ?? defaultExaminer}");
    }

    private static void AppendExhibitTable(Body body, IReadOnlyList<Exhibit> exhibits)
    {
        var table = new Table();
        var tableProps = new TableProperties(
            new TableBorders(
                new TopBorder { Val = BorderValues.Single, Size = 4 },
                new BottomBorder { Val = BorderValues.Single, Size = 4 },
                new LeftBorder { Val = BorderValues.Single, Size = 4 },
                new RightBorder { Val = BorderValues.Single, Size = 4 },
                new InsideHorizontalBorder { Val = BorderValues.Single, Size = 4 },
                new InsideVerticalBorder { Val = BorderValues.Single, Size = 4 }),
            new TableLayout { Type = TableLayoutValues.Autofit });
        table.AppendChild(tableProps);

        // Header row.
        table.AppendChild(BuildRow(["ID", "Title", "Type", "Captured", "SHA-256"], header: true));
        foreach (var e in exhibits)
        {
            table.AppendChild(BuildRow(
                [e.Id, e.Title, e.Kind.ToString(),
                 e.CapturedUtc.ToString("u", CultureInfo.InvariantCulture),
                 e.Sha256 ?? "—"]));
        }
        body.AppendChild(table);
    }

    private static TableRow BuildRow(IReadOnlyList<string> cells, bool header = false)
    {
        var row = new TableRow();
        foreach (var c in cells)
        {
            var run = new Run(new Text(c) { Space = SpaceProcessingModeValues.Preserve });
            if (header)
            {
                run.PrependChild(new RunProperties(new Bold(), new Color { Val = "FF7A1A" }));
            }
            var cellPara = new Paragraph(run);
            var cell = new TableCell(cellPara);
            row.AppendChild(cell);
        }
        return row;
    }

    private enum BlockKind { Paragraph, Bullet, Heading }

    private static IEnumerable<(BlockKind, string)> BlocksFromMarkdown(string md)
    {
        if (string.IsNullOrWhiteSpace(md)) yield break;
        var paragraph = new System.Text.StringBuilder();
        foreach (var raw in md.Replace("\r\n", "\n").Split('\n'))
        {
            var line = raw.TrimEnd();
            if (string.IsNullOrWhiteSpace(line))
            {
                if (paragraph.Length > 0)
                {
                    yield return (BlockKind.Paragraph, paragraph.ToString().Trim());
                    paragraph.Clear();
                }
                continue;
            }
            if (line.StartsWith("- ", StringComparison.Ordinal) || line.StartsWith("* ", StringComparison.Ordinal))
            {
                if (paragraph.Length > 0)
                {
                    yield return (BlockKind.Paragraph, paragraph.ToString().Trim());
                    paragraph.Clear();
                }
                yield return (BlockKind.Bullet, line[2..].Trim());
                continue;
            }
            if (line.StartsWith("# ", StringComparison.Ordinal) ||
                line.StartsWith("## ", StringComparison.Ordinal) ||
                line.StartsWith("### ", StringComparison.Ordinal))
            {
                if (paragraph.Length > 0)
                {
                    yield return (BlockKind.Paragraph, paragraph.ToString().Trim());
                    paragraph.Clear();
                }
                yield return (BlockKind.Heading, line.TrimStart('#', ' '));
                continue;
            }
            paragraph.AppendLine(line);
        }
        if (paragraph.Length > 0)
        {
            yield return (BlockKind.Paragraph, paragraph.ToString().Trim());
        }
    }

    private static string ResolveTemplateName(string id) =>
        ReportTemplates.All.FirstOrDefault(t => t.Id == id)?.Name ?? id;
}
